### ISSUE TITLE
UX issue with "space" shortcut [1]

### ISSUE THREAD

**Issue by nicoespeon** [christian-fei/pomodoro#91]
Here is the problem I ran a couple of time:

- use the "space" shortcut to launch pomodoro timer
- after pomodoro, clicked on the "break" timer to give me 5mins break. No shortcut for that as far as I know
- after break, press "space" again to launch the pomodoro timer as I'm used to

But since the focus was on the last clicked button, pressing space actually launch the timer break instead of the pomodoro.

Suggested solutions:

- use another shorcut to prevent conflicts with default behavior
- prevent default behavior when the focus is on a button
- focus-out the clicked button when timer is over

I don't know which sounds best. Did you experiment same issues? :)

**Comment by christian-fei** [comment]
Thank you!
Yeah this bugged me too sometimes..
I'm not sure if it makes sense to prevent the default behaviour on a button (e.g. preventDefault) since it's a usability 'feature'.
But i very much like the idea to remove the focus when the timer is over, or simply after an action is taken (like when you started the pomodoro, i remove the focus)!

**Comment by nicoespeon** [comment]
It works like a charm, thanks! :+1:
